---
services:
  migrate:
    image: quay.io/wikipedialibrary/twlight:branch_production
    depends_on:
      - 'db'
    volumes:
      - type: bind
        source: /data/project/prod
        target: /app/backup
      - type: bind
        source: ./media
        target: /app/media
    secrets:
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
      - DKIM_PRIVATE_KEY
      - SECRET_KEY
      - TWLIGHT_OAUTH_CONSUMER_KEY
      - TWLIGHT_OAUTH_CONSUMER_SECRET
      - TWLIGHT_EZPROXY_SECRET
    env_file:
      - ./conf/production.twlight.env
    command: >
      bash -c "/app/bin/twlight_backup.sh && /app/bin/virtualenv_migrate.sh"
    restart: on-failure
  twlight:
    image: quay.io/wikipedialibrary/twlight:branch_production
    depends_on:
      - 'migrate'
    volumes:
      - type: bind
        source: /data/project/prod
        target: /app/backup
    env_file:
      - ./conf/production.twlight.env
  web:
    volumes:
      - type: volume
        target: /var/lib/nginx/cache
      - type: bind
        source: ./conf/production.nginx.conf
        target: /etc/nginx/conf.d/default.conf
secrets:
  DJANGO_DB_NAME:
    external: true
  DJANGO_DB_USER:
    external: true
  DJANGO_DB_PASSWORD:
    external: true
  DKIM_PRIVATE_KEY:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
  SECRET_KEY:
    external: true
  TWLIGHT_OAUTH_CONSUMER_KEY:
    external: true
  TWLIGHT_OAUTH_CONSUMER_SECRET:
    external: true
  TWLIGHT_EZPROXY_SECRET:
    external: true
  MW_API_EMAIL_USER:
    external: true
  MW_API_EMAIL_PASSWORD:
    external: true
